version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dashboard_simontov_app
        volumes:
            - .:/var/www/html
        ports:
            - '80'

    nginx:
        image: nginx:alpine
        container_name: nginx_simontov_app
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - app
