version: '3'

services:
  simontov_admin:
    build:
      context: .
      dockerfile: Dockerfile  # Use the custom Dockerfile
    container_name: simontov_admin
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api_default

networks:
  api_default:
    external: true
